<?
/*********************************************************************************************************
 This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Info del Archivo";
  $msg['name']          = "Nombre";
  $msg['size']          = "Tamaño";
  $msg['lastChange']    = "Modificación";
  $msg['owner']         = "Propietario";
  $msg['group']         = "Grupo";
  $msg['other']         = "Otro";
  $msg['read']          = "Leer";
  $msg['write']         = "Escribir";
  $msg['execute']       = "Ejecutar";
  $msg['permissions']   = "Permisos";
  $msg['error']         = "ERROR";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Reset";
  $msg['cmdSave']       = "Guardar";
  $msg['cmdViewList']   = "Ver Lista";
  $msg['cmdGetFile']    = "Bajar Archivo";
  $msg['cmdRename']     = "Renombrar";
  $msg['cmdDelete']     = "Borrar";
  $msg['cmdEdit']       = "Editar";
  $msg['cmdChangePerm'] = "Cambiar Permisos";
  $msg['cmdFileInfo']   = "Ver Info";
  $msg['cmdUploadFile'] = "Subir Archivo";
  $msg['cmdChangeDir']  = "Cambiar Directorio";
  $msg['cmdParentDir']  = "Cambiar Directorio";
  $msg['cmdNewDir']     = "Nuevo Directorio";
  $msg['cmdSortAsc']    = "Ordenar Ascendente";
  $msg['cmdSortDesc']   = "Ordenar Descendente";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "No puedes cambiar los permisos";
  $msg['errDirNew']     = "Error al crear el Directorio";
  $msg['errOpen']       = "Error al abrir";
  $msg['errSave']       = "Error al guardar";
  $msg['errDelete']     = "Error al borrar";
  $msg['errRename']     = "Error al renombrar";
  $msg['errDisabled']   = "Esta función está desactivada";
  $msg['errConnect']    = "No es posible conectar al servidor FTP";
  $msg['errLogin']      = "Fallo en el login";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "¿Eliminar el Directorio definitivamente?";
  $msg['msgDeleteFile'] = "¿Eliminar el archivo definitivamente?";
  $msg['msgSaveFile']   = "¿Guardar y sobreescribir el archivo existente?";

//========================================================================================================
?>
